# Website's icon url.
favicon: https://s1.ax1x.com/2020/07/25/aSC9Cn.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:

article:
  # Show word count and estimated reading time.
  readtime: false
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light

# Navigation bar menu links.
menu:
  Home: /
  归档: /archives
  操作系统: /categories/操作系统
  分布式: /categories/分布式
  算法设计:  /categories/算法设计
  随记:  /categories/随记
  NLP: /categories/NLP
  机器学习: /categories/机器学习
  # About: /about

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: false

# Share plugin settings.
share:
  type: 
  install_url:

# Comment plugin settings.
comment:
  type: valine
  app_id: DEXiOMuMN86LKmdUtJYX4FRL-MdYXbMMI        # (required) LeanCloud application id
  app_key: tPt6E0GhkwXKEBUacbugDcWb       # (required) LeanCloud application key
  notify: false           # (optional) receive email notification
  verify: false           # (optional) show verification code
  # placeholder: xxxxxxxx   # (optional) comment box placeholder text


# Other plugins and their settings.
plugins:
  mathjax: true
  katex: true
  gallery: true
  clipboard: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/blackredscarf

# Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/blackredscarf
